[build]
  command = "npm run build"
  publish = "dist/client"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["dist/server/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/site"
  status = 200
  force = false

